[build]
  command = "CI=false npm run build" # Disable treating warnings as errors
  publish = "build"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
